import React from 'react';
import { Image, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { formatMadPrice } from '../../commerce/cartState';
import { PrototypeOrder } from '../../commerce/orderState';
import { MayushLogo } from '../../design-system/components/brand/MayushLogo';
import { MayushIcon } from '../../design-system/components/navigation/MayushIcon';
import { MayushText } from '../../design-system/components/typography/MayushText';
import { colors } from '../../design-system/tokens/colors';

const PRODUCT = require('../../../assets/reference-art/home-new-luna.png');
export const OrderDetailsScreen: React.FC<{ order: PrototypeOrder; onBack: () => void }> = ({ order, onBack }) => <View style={styles.screen} accessibilityLabel="Détails de la commande"><View style={styles.header}><TouchableOpacity accessibilityRole="button" onPress={onBack}><MayushIcon name="arrow-left" size={25} color={colors.brand.navy900} /></TouchableOpacity><MayushLogo width={131} height={39} /><View style={styles.headerSpace} /></View><MayushText variant="pageTitle" color={colors.brand.navy900} align="center" style={styles.title}>Détails de la commande</MayushText><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.statusCard}><Meta icon="clipboard" label="RÉFÉRENCE DE COMMANDE" value={order.id} /><Meta icon="shield" label="STATUT DE PAIEMENT" value={order.paymentStatus} success /><Meta icon="calendar" label="DATE DE CRÉATION" value={order.createdAtLabel} /><Meta icon="clock" label="STATUT ACTUEL" value={order.deliveryStatus} accent /></View><View style={styles.timeline}><Timeline label="Confirmée" done /><Timeline label="En préparation" active /><Timeline label="Expédiée" /><Timeline label="Livrée" /></View><View style={styles.card}><MayushText variant="strongBody" color={colors.brand.navy900}>Articles commandés</MayushText>{order.lines.map((line) => <View key={line.id} style={styles.line}><Image source={line.imageUri ? { uri: line.imageUri } : PRODUCT} style={styles.image} /><View style={styles.lineCopy}><MayushText variant="strongBody" color={colors.brand.navy900}>{line.name}</MayushText><MayushText variant="caption" color={colors.neutral.gray700}>{line.variant}</MayushText><MayushText variant="caption" color={colors.neutral.gray700}>Qté : {line.quantity}</MayushText></View><MayushText variant="strongBody" color={colors.brand.navy900}>{formatMadPrice(line.unitPriceMad * line.quantity)}</MayushText></View>)}</View><View style={styles.delivery}><Meta icon="map-pin" label="Adresse de livraison" value={`${order.address.addressLine}\n${order.address.city} ${order.address.postcode}, Maroc`} /><Meta icon="truck-outline" label="Mode de livraison" value="Mayush Delivery\nLivraison estimée" /></View><View style={styles.total}><MayushText variant="sectionTitle" color={colors.brand.navy900}>Total payé</MayushText><MayushText variant="sectionTitle" color={colors.brand.orange500}>{formatMadPrice(order.totalMad)}</MayushText></View><TouchableOpacity accessibilityRole="button" style={styles.cancel}><MayushIcon name="trash-2" size={16} color={colors.semantic.error} /><MayushText variant="button" color={colors.semantic.error}>Annuler la commande</MayushText></TouchableOpacity><TouchableOpacity accessibilityRole="button" style={styles.support}><MayushIcon name="phone" size={16} color={colors.brand.navy900} /><MayushText variant="button" color={colors.brand.navy900}>Contacter le support</MayushText></TouchableOpacity></ScrollView></View>;
const Meta: React.FC<{ icon: React.ComponentProps<typeof MayushIcon>['name']; label: string; value: string; success?: boolean; accent?: boolean }> = ({ icon, label, value, success, accent }) => <View style={styles.meta}><View style={styles.metaIcon}><MayushIcon name={icon} size={19} color={success ? colors.semantic.success : accent ? colors.brand.orange500 : colors.brand.orange500} /></View><View style={styles.metaCopy}><MayushText variant="caption" color={colors.neutral.gray700}>{label}</MayushText><MayushText variant="strongBody" color={success ? colors.semantic.success : accent ? colors.brand.orange500 : colors.brand.navy900} style={styles.metaValue}>{value}</MayushText></View></View>;
const Timeline: React.FC<{ label: string; done?: boolean; active?: boolean }> = ({ label, done, active }) => <View style={styles.time}><View style={[styles.timeCircle, (done || active) && styles.timeCircleActive]}>{done ? <MayushIcon name="check" size={15} color={colors.surface.white} /> : active ? <MayushIcon name="package-variant-closed" size={15} color={colors.surface.white} /> : <MayushIcon name="check" size={15} color={colors.neutral.gray700} />}</View><MayushText variant="caption" color={active ? colors.brand.orange500 : colors.brand.navy900} align="center">{label}</MayushText></View>;
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFFDF9' }, header: { height: 70, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerSpace: { width: 25 }, title: { fontSize: 20 }, content: { padding: 19, gap: 8 }, statusCard: { borderWidth: 1, borderColor: '#F0E3D7', borderRadius: 8, padding: 10, flexDirection: 'row', flexWrap: 'wrap' }, meta: { width: '50%', minHeight: 52, flexDirection: 'row', alignItems: 'flex-start', gap: 7, padding: 5 }, metaIcon: { width: 27, height: 27, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF5EA' }, metaCopy: { flex: 1 }, metaValue: { marginTop: 2, fontSize: 11, lineHeight: 15 }, timeline: { height: 62, borderRadius: 8, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.surface.white }, time: { width: 63, alignItems: 'center', gap: 4 }, timeCircle: { width: 23, height: 23, borderRadius: 12, borderWidth: 1, borderColor: colors.neutral.gray300, alignItems: 'center', justifyContent: 'center' }, timeCircleActive: { borderColor: colors.brand.orange500, backgroundColor: colors.brand.orange500 }, card: { borderWidth: 1, borderColor: '#F0E3D7', borderRadius: 8, padding: 10, gap: 8, backgroundColor: colors.surface.white }, line: { minHeight: 57, flexDirection: 'row', alignItems: 'center', gap: 8 }, image: { width: 72, height: 54, borderRadius: 4, backgroundColor: colors.surface.cream }, lineCopy: { flex: 1, gap: 2 }, delivery: { borderWidth: 1, borderColor: '#F0E3D7', borderRadius: 8, padding: 8, flexDirection: 'row' }, total: { minHeight: 50, borderRadius: 8, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.surface.white }, cancel: { height: 33, borderWidth: 1, borderColor: colors.semantic.error, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, support: { height: 33, borderWidth: 1, borderColor: colors.brand.navy900, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 } });
