import React from 'react';
import { Image, ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { formatMadPrice } from '../../commerce/cartState';
import { PrototypeOrder } from '../../commerce/orderState';
import { BottomTabBar, TabKey } from '../../design-system/components/navigation/BottomTabBar';
import { MayushLogo } from '../../design-system/components/brand/MayushLogo';
import { MayushIcon } from '../../design-system/components/navigation/MayushIcon';
import { MayushText } from '../../design-system/components/typography/MayushText';
import { useTheme } from '../../design-system/theme/useTheme';
import { colors } from '../../design-system/tokens/colors';

const PRODUCT = require('../../../assets/reference-art/home-new-luna.png');
export interface OrdersListScreenProps { orders: PrototypeOrder[]; onOpenOrder: (orderId: string) => void; onNavigateTab: (tab: TabKey) => void; }
export const OrdersListScreen: React.FC<OrdersListScreenProps> = ({ orders, onOpenOrder, onNavigateTab }) => {
  const { language } = useTheme();
  const copy = language === 'ar' ? { title: '\u0637\u0644\u0628\u0627\u062a\u064a', subtitle: '\u062a\u0627\u0628\u0639 \u0633\u062c\u0644 \u0637\u0644\u0628\u0627\u062a\u0643.', all: '\u0627\u0644\u0643\u0644', inProgress: '\u0642\u064a\u062f \u0627\u0644\u062a\u0646\u0641\u064a\u0630', completed: '\u0645\u0643\u062a\u0645\u0644\u0629', cancelled: '\u0645\u0644\u063a\u0627\u0629', details: '\u0639\u0631\u0636 \u0627\u0644\u062a\u0641\u0627\u0635\u064a\u0644', empty: '\u0644\u0627 \u062a\u0648\u062c\u062f \u0637\u0644\u0628\u0627\u062a \u062d\u062a\u0649 \u0627\u0644\u0622\u0646.' } : { title: 'Mes commandes', subtitle: 'Consultez l’historique de toutes vos commandes.', all: 'Toutes', inProgress: 'En cours', completed: 'Terminées', cancelled: 'Annulées', details: 'Voir les détails', empty: 'Aucune commande pour le moment.' };
  return <View style={styles.screen} accessibilityLabel={copy.title}><View style={styles.header}><MayushLogo width={145} height={43} /><MayushIcon name="bell" size={25} color={colors.brand.navy900} /></View><MayushText variant="display" color={colors.brand.navy900} align="center" style={styles.title}>{copy.title}</MayushText><MayushText variant="body" color={colors.neutral.gray700} align="center" style={styles.subtitle}>{copy.subtitle}</MayushText><View style={styles.search}><MayushIcon name="search" size={18} color={colors.neutral.gray700} /><MayushText variant="caption" color={colors.neutral.gray700}>{language === 'ar' ? '\u0627\u0628\u062d\u062b \u0628\u0631\u0642\u0645 \u0627\u0644\u0637\u0644\u0628' : 'Rechercher par numéro de commande'}</MayushText></View><View style={styles.tabs}><Tab label={copy.all} active /><Tab label={copy.inProgress} /><Tab label={copy.completed} /><Tab label={copy.cancelled} /></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.list}>{orders.length ? orders.map((order) => <OrderCard key={order.id} order={order} label={copy.details} onPress={() => onOpenOrder(order.id)} />) : <MayushText variant="body" color={colors.neutral.gray700} align="center" style={styles.empty}>{copy.empty}</MayushText>}</ScrollView><BottomTabBar activeTab="account" onTabPress={onNavigateTab} cartBadgeCount={0} /></View>;
};
const Tab: React.FC<{ label: string; active?: boolean }> = ({ label, active }) => <View style={[styles.tab, active && styles.tabActive]}><MayushText variant="caption" color={active ? colors.brand.orange500 : colors.brand.navy900}>{label}</MayushText></View>;
const OrderCard: React.FC<{ order: PrototypeOrder; label: string; onPress: () => void }> = ({ order, label, onPress }) => <View style={styles.card}><View style={styles.cardTop}><View><MayushText variant="strongBody" color={colors.brand.navy900}>{order.id}</MayushText><MayushText variant="caption" color={colors.neutral.gray700}>{order.createdAtLabel}</MayushText></View><View style={styles.status}><MayushIcon name="clock" size={14} color={colors.brand.orange500} /><MayushText variant="caption" color={colors.brand.orange500}>En cours</MayushText></View></View><View style={styles.images}>{order.lines.slice(0, 3).map((line) => <Image key={line.id} source={line.imageUri ? { uri: line.imageUri } : PRODUCT} style={styles.product} />)}<MayushText variant="caption" color={colors.neutral.gray700}>{order.lines.length} articles</MayushText><MayushText variant="sectionTitle" color={colors.brand.orange500} style={styles.amount}>{formatMadPrice(order.totalMad)}</MayushText></View><View style={styles.cardBottom}><View><MayushText variant="caption" color={colors.semantic.success}>✓ Paiement</MayushText><MayushText variant="caption" color={colors.semantic.success}>Payé</MayushText></View><View><MayushText variant="caption" color={colors.brand.orange500}>Livraison</MayushText><MayushText variant="caption" color={colors.brand.orange500}>En cours</MayushText></View><TouchableOpacity accessibilityRole="button" onPress={onPress} style={styles.detailButton}><MayushText variant="caption" color={colors.brand.orange500}>{label}</MayushText><MayushIcon name="chevron-right" size={14} color={colors.brand.orange500} /></TouchableOpacity></View></View>;
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFFDF9' }, header: { height: 72, paddingHorizontal: 25, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { marginTop: 2, fontSize: 29, lineHeight: 34 }, subtitle: { marginTop: 2, fontSize: 12 }, search: { height: 36, marginTop: 11, marginHorizontal: 27, paddingHorizontal: 12, borderWidth: 1, borderColor: colors.neutral.gray300, borderRadius: 9, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: colors.surface.white }, tabs: { height: 39, marginTop: 4, paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.surface.borderWarm }, tab: { minWidth: 57, alignItems: 'center', justifyContent: 'center' }, tabActive: { borderBottomWidth: 2, borderBottomColor: colors.brand.orange500 }, list: { padding: 11, gap: 9 }, card: { borderWidth: 1, borderColor: '#F0E3D7', borderRadius: 8, padding: 11, backgroundColor: colors.surface.white, shadowColor: colors.brand.navy900, shadowOpacity: 0.06, shadowRadius: 7, shadowOffset: { width: 0, height: 2 }, elevation: 2 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between' }, status: { height: 23, borderRadius: 5, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#FFF5E9' }, images: { minHeight: 47, marginTop: 7, flexDirection: 'row', alignItems: 'center', gap: 4 }, product: { width: 47, height: 40, borderRadius: 4, backgroundColor: colors.surface.cream }, amount: { marginLeft: 'auto', fontSize: 15 }, cardBottom: { marginTop: 7, paddingTop: 7, borderTopWidth: 1, borderTopColor: colors.surface.borderWarm, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, detailButton: { height: 27, borderWidth: 1, borderColor: colors.brand.orange500, borderRadius: 5, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 3 }, empty: { marginTop: 50 } });
