import React from 'react';
import { StyleSheet, TouchableOpacity, View } from 'react-native';
import { MayushIcon } from '../../design-system/components/navigation/MayushIcon';
import { MayushText } from '../../design-system/components/typography/MayushText';
import { colors } from '../../design-system/tokens/colors';
import { OrderActionButton, OrderScreenHeader } from './OrderScreenComponents';

export const ORDER_LIST_SKELETON_SECTIONS = ['search', 'tabs', 'order-card-1', 'order-card-2', 'order-card-3'] as const;
export const ORDER_DETAIL_SKELETON_SECTIONS = ['summary', 'timeline', 'products', 'address', 'payment', 'totals', 'actions'] as const;

const EmptyLayout: React.FC<{ icon: 'search' | 'box' | 'alert-circle'; title: string; body: string; children: React.ReactNode }> = ({ icon, title, body, children }) => <View style={styles.screen}><View style={styles.canvas}><View style={styles.logo}><MayushText variant="pageTitle" color={colors.brand.navy900}>M<MayushText variant="pageTitle" color={colors.brand.orange500}>A</MayushText>YUSH</MayushText></View><View style={styles.center}><View style={styles.illustration}><MayushIcon name={icon} size={62} color={colors.brand.orange500} /></View><MayushText variant="pageTitle" color={colors.brand.navy900} align="center">{title}</MayushText><MayushText variant="body" color={colors.neutral.gray700} align="center">{body}</MayushText><View style={styles.actions}>{children}</View></View></View></View>;

export const OrderNotFoundScreen: React.FC<{ orderId?: string | null; onOrders: () => void; onSupport: () => void }> = ({ orderId, onOrders, onSupport }) => <EmptyLayout icon="search" title="Commande introuvable" body={`Nous n’avons trouvé aucune commande correspondant ${orderId ? `au numéro ${orderId}` : 'à ce numéro'}. Vérifiez le numéro saisi et réessayez.`}><OrderActionButton label="Voir mes commandes" icon="clipboard" onPress={onOrders} primary /><OrderActionButton label="Contacter le support" icon="headphones" onPress={onSupport} /></EmptyLayout>;
export const OrdersEmptyScreen: React.FC<{ onDiscover: () => void; onFavorites: () => void }> = ({ onDiscover, onFavorites }) => <EmptyLayout icon="box" title="Vous n’avez pas encore de commande" body="Pas encore d’achat ? C’est le moment idéal pour trouver des pièces uniques qui sublimeront votre intérieur."><OrderActionButton label="Découvrir les collections" icon="sofa" onPress={onDiscover} primary /><OrderActionButton label="Voir mes favoris" icon="heart" onPress={onFavorites} /></EmptyLayout>;
export const OrdersErrorScreen: React.FC<{ onRetry: () => void; onAccount: () => void }> = ({ onRetry, onAccount }) => <EmptyLayout icon="alert-circle" title="Impossible de charger vos commandes" body="Nous rencontrons un problème de connexion. Veuillez vérifier votre réseau et réessayer."><OrderActionButton label="Réessayer" icon="rotate-ccw" onPress={onRetry} primary /><OrderActionButton label="Retourner à mon compte" icon="user" onPress={onAccount} /></EmptyLayout>;

const Bar: React.FC<{ width: `${number}%`; height?: number; orange?: boolean }> = ({ width, height = 12, orange }) => <View style={[styles.bar, { width, height }, orange && styles.orange]} />;
const SkeletonCard: React.FC<{ detail?: boolean }> = ({ detail }) => <View style={styles.card}><View style={styles.row}><View style={styles.square} /><View style={styles.grow}><Bar width="72%" /><Bar width="46%" /></View><Bar width="22%" /></View>{detail ? <><View style={styles.divider} /><Bar width="100%" height={42} /><Bar width="84%" /></> : <View style={styles.row}><View style={styles.thumb} /><View style={styles.thumb} /><View style={styles.thumb} /><View style={styles.grow}><Bar width="86%" /><Bar width="64%" /></View></View>}</View>;
export const OrdersSkeletonScreen: React.FC = () => <View style={styles.screen}><View style={styles.canvas}><OrderScreenHeader onBack={() => undefined} showBell title="Mes commandes" subtitle="Suivez l’état de toutes vos commandes." /><View style={styles.skeletonContent}><View style={styles.search}><Bar width="68%" /></View><View style={styles.row}>{[38,28,30,24].map((w) => <Bar key={w} width={`${w}%`} />)}</View>{[1,2,3].map((key) => <SkeletonCard key={key} />)}</View></View></View>;
export const OrderDetailSkeletonScreen: React.FC<{ onBack: () => void }> = ({ onBack }) => <View style={styles.screen}><View style={styles.canvas}><View style={styles.detailHeader}><TouchableOpacity onPress={onBack}><MayushIcon name="arrow-left" size={24} color={colors.brand.navy900} /></TouchableOpacity><MayushText variant="sectionTitle" color={colors.brand.navy900}>MAYUSH</MayushText><MayushIcon name="bell" size={22} color={colors.brand.navy900} /></View><View style={styles.skeletonContent}><SkeletonCard detail />{['Produits commandés','Adresse de livraison','Mode de paiement','Récapitulatif de la commande'].map((label) => <View key={label} style={styles.card}><MayushText variant="strongBody" color={colors.brand.navy900}>{label}</MayushText><Bar width="82%" /><Bar width="58%" /></View>)}<Bar width="100%" height={42} orange /><Bar width="100%" height={42} /></View></View></View>;

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFFDF9' }, canvas: { flex: 1, width: '100%', maxWidth: 393, alignSelf: 'center' }, logo: { alignItems: 'center', paddingTop: 48 }, center: { flex: 1, justifyContent: 'center', padding: 36, gap: 18 }, illustration: { width: 142, height: 142, borderRadius: 71, backgroundColor: '#FFF4E9', alignSelf: 'center', alignItems: 'center', justifyContent: 'center' }, actions: { gap: 10, marginTop: 24 }, detailHeader: { height: 92, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, skeletonContent: { padding: 20, gap: 10 }, search: { height: 38, borderRadius: 8, backgroundColor: colors.surface.white, justifyContent: 'center', paddingHorizontal: 12 }, card: { padding: 13, borderRadius: 10, backgroundColor: colors.surface.white, gap: 10, borderWidth: 1, borderColor: '#F4EEE8' }, row: { flexDirection: 'row', gap: 9, alignItems: 'center' }, grow: { flex: 1, gap: 8 }, bar: { borderRadius: 8, backgroundColor: '#ECEDEF' }, orange: { backgroundColor: colors.brand.orange500 }, square: { width: 42, height: 42, borderRadius: 8, backgroundColor: '#F0F1F2' }, thumb: { width: 62, height: 46, borderRadius: 6, backgroundColor: '#ECEDEF' }, divider: { height: 1, backgroundColor: '#EEE7E0' } });
