import React, { useState } from 'react';
import { Image, ScrollView, StyleSheet, View } from 'react-native';
import { formatMadPrice } from '../../commerce/cartState';
import { BuyerOrder } from '../../commerce/orderState';
import { MayushIcon } from '../../design-system/components/navigation/MayushIcon';
import { MayushText } from '../../design-system/components/typography/MayushText';
import { useTheme } from '../../design-system/theme/useTheme';
import { colors } from '../../design-system/tokens/colors';
import { formatOrderDate, getOrderLineImage, OrderActionButton, OrderCard, OrderScreenHeader } from './OrderScreenComponents';

export const OrderInvoiceScreen: React.FC<{
  order: BuyerOrder;
  onBack: () => void;
  onOpenOrder: () => void;
}> = ({ order, onBack, onOpenOrder }) => {
  const { language, isRTL } = useTheme();
  const [operationNotice, setOperationNotice] = useState<string | null>(null);
  const invoice = order.invoice;
  const copy = language === 'ar' ? {
    title: 'الفاتورة', subtitle: 'تفاصيل معاينة الفاتورة', order: 'رقم الطلب', invoice: 'رقم الفاتورة', billing: 'معلومات الفوترة', name: 'الاسم', email: 'البريد الإلكتروني', phone: 'الهاتف', address: 'عنوان الفوترة', products: 'المنتجات', quantity: 'الكمية', total: 'المجموع', subtotal: 'المجموع الفرعي', delivery: 'رسوم التوصيل', discount: 'الخصم', download: 'تنزيل الفاتورة', share: 'مشاركة', details: 'عرض تفاصيل طلبي', unavailable: 'معاينة الفاتورة متاحة، لكن إنشاء ملف PDF والمشاركة غير مربوطين بعد.', noInvoice: 'لا توجد معاينة فاتورة لهذا الطلب.',
  } : {
    title: 'Facture', subtitle: 'Détails de votre aperçu de facture', order: 'Numéro de commande', invoice: 'Numéro de facture', billing: 'Informations de facturation', name: 'Nom', email: 'Email', phone: 'Téléphone', address: 'Adresse de facturation', products: 'Produits', quantity: 'Qté', total: 'Total', subtotal: 'Sous-total', delivery: 'Frais de livraison', discount: 'Réduction', download: 'Télécharger la facture', share: 'Partager', details: 'Voir le détail de ma commande', unavailable: 'L’aperçu de facture est disponible, mais la génération PDF et le partage ne sont pas encore intégrés.', noInvoice: 'Aucun aperçu de facture n’est disponible pour cette commande.',
  };
  const row = isRTL ? styles.rowReverse : styles.row;
  if (!invoice) return <View style={styles.screen}><View style={styles.canvas}><OrderScreenHeader onBack={onBack} title={copy.title} subtitle={copy.noInvoice} /><View style={styles.empty}><OrderActionButton label={copy.details} icon="file-text" onPress={onOpenOrder} /></View></View></View>;
  const subtotal = order.totalMad - order.deliveryFeeMad + order.discountMad;
  const showBoundary = () => setOperationNotice(copy.unavailable);
  return <View style={styles.screen} accessibilityLabel={`${copy.title} ${invoice.invoiceNumber}`}><View style={styles.canvas}><OrderScreenHeader onBack={onBack} title={copy.title} subtitle={copy.subtitle} /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <OrderCard><View style={[row, styles.identity]}><Fact label={copy.order} value={order.orderId} detail={formatOrderDate(order.createdAt, language)} isRTL={isRTL} /><Fact label={copy.invoice} value={invoice.invoiceNumber} detail={formatOrderDate(invoice.issuedAt, language)} isRTL={isRTL} /></View></OrderCard>
    <OrderCard><MayushText variant="sectionTitle" color={colors.brand.navy900} style={styles.sectionTitle}>{copy.billing}</MayushText><View style={[row, styles.billing]}><View style={styles.flex}><BillingLine icon="user" label={copy.name} value={invoice.billingName} isRTL={isRTL} />{invoice.billingEmail ? <BillingLine icon="mail" label={copy.email} value={invoice.billingEmail} isRTL={isRTL} /> : null}{invoice.billingPhone ? <BillingLine icon="phone" label={copy.phone} value={invoice.billingPhone} isRTL={isRTL} /> : null}</View><View style={styles.flex}><BillingLine icon="map-pin" label={copy.address} value={`${invoice.billingAddress.addressLine}\n${invoice.billingAddress.zone}\n${invoice.billingAddress.city} ${invoice.billingAddress.postcode}`} isRTL={isRTL} /></View></View></OrderCard>
    <OrderCard><View style={styles.tableHead}><MayushText variant="caption" color={colors.neutral.gray700}>{copy.products.toUpperCase()}</MayushText><MayushText variant="caption" color={colors.neutral.gray700}>{copy.quantity.toUpperCase()}</MayushText><MayushText variant="caption" color={colors.neutral.gray700}>{copy.total.toUpperCase()}</MayushText></View>{order.lines.map((line) => <View key={line.orderLineId} style={[row, styles.invoiceLine]}><Image source={getOrderLineImage(line)} style={styles.image} /><View style={styles.lineCopy}><MayushText variant="strongBody" color={colors.brand.navy900} align={isRTL ? 'right' : 'left'}>{line.name}</MayushText><MayushText variant="caption" color={colors.neutral.gray700} align={isRTL ? 'right' : 'left'}>{line.variantLabel}</MayushText></View><MayushText variant="body" color={colors.brand.navy900}>{line.quantity}</MayushText><MayushText variant="strongBody" color={colors.brand.navy900}>{formatMadPrice(line.unitPriceMad * line.quantity)}</MayushText></View>)}<SummaryLine label={copy.subtotal} value={formatMadPrice(subtotal)} strong={false} /><SummaryLine label={copy.delivery} value={formatMadPrice(order.deliveryFeeMad)} strong={false} />{order.discountMad ? <SummaryLine label={copy.discount} value={`- ${formatMadPrice(order.discountMad)}`} strong={false} success /> : null}<SummaryLine label={copy.total} value={formatMadPrice(order.totalMad)} strong /></OrderCard>
    <View style={[row, styles.actions]}><View style={styles.flex}><OrderActionButton label={copy.download} icon="download" onPress={showBoundary} primary /></View><View style={styles.flex}><OrderActionButton label={copy.share} icon="share" onPress={showBoundary} /></View></View>
    {operationNotice ? <View style={[row, styles.notice]}><MayushIcon name="info" size={20} color={colors.semantic.info} /><MayushText variant="caption" color={colors.neutral.gray700} align={isRTL ? 'right' : 'left'} style={styles.flex}>{operationNotice}</MayushText></View> : null}
    <OrderActionButton label={copy.details} icon="file-text" onPress={onOpenOrder} />
  </ScrollView></View></View>;
};

const Fact: React.FC<{ label: string; value: string; detail: string; isRTL: boolean }> = ({ label, value, detail, isRTL }) => <View style={styles.flex}><MayushText variant="caption" color={colors.neutral.gray700} align={isRTL ? 'right' : 'left'}>{label.toUpperCase()}</MayushText><MayushText variant="sectionTitle" color={colors.brand.navy900} align={isRTL ? 'right' : 'left'}>{value}</MayushText><MayushText variant="body" color={colors.neutral.gray700} align={isRTL ? 'right' : 'left'}>{detail}</MayushText></View>;
const BillingLine: React.FC<{ icon: 'user' | 'mail' | 'phone' | 'map-pin'; label: string; value: string; isRTL: boolean }> = ({ icon, label, value, isRTL }) => <View style={[isRTL ? styles.rowReverse : styles.row, styles.billingLine]}><View style={styles.iconCircle}><MayushIcon name={icon} size={18} color={colors.brand.orange500} /></View><View style={styles.flex}><MayushText variant="caption" color={colors.neutral.gray700} align={isRTL ? 'right' : 'left'}>{label}</MayushText><MayushText variant="body" color={colors.brand.navy900} align={isRTL ? 'right' : 'left'}>{value}</MayushText></View></View>;
const SummaryLine: React.FC<{ label: string; value: string; strong: boolean; success?: boolean }> = ({ label, value, strong, success }) => <View style={[styles.summary, strong && styles.summaryStrong]}><MayushText variant={strong ? 'sectionTitle' : 'body'} color={success ? colors.semantic.success : colors.brand.navy900}>{label}</MayushText><MayushText variant={strong ? 'sectionTitle' : 'body'} color={strong ? colors.brand.orange500 : success ? colors.semantic.success : colors.brand.navy900}>{value}</MayushText></View>;
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFDF9' }, canvas: { flex: 1, width: '100%', maxWidth: 393, alignSelf: 'center' }, content: { padding: 14, paddingBottom: 28, gap: 10 }, empty: { padding: 18 }, row: { flexDirection: 'row' }, rowReverse: { flexDirection: 'row-reverse' }, flex: { flex: 1 }, identity: { gap: 20 }, sectionTitle: { marginBottom: 12 }, billing: { gap: 14 }, billingLine: { gap: 8, marginBottom: 10, alignItems: 'flex-start' }, iconCircle: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF3E7' },
  tableHead: { flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 8 }, invoiceLine: { minHeight: 68, gap: 7, alignItems: 'center', paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: colors.surface.borderWarm }, image: { width: 63, height: 52, borderRadius: 6, backgroundColor: colors.surface.cream }, lineCopy: { flex: 1, gap: 2 }, summary: { minHeight: 29, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, summaryStrong: { marginTop: 5, paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.surface.borderWarm }, actions: { gap: 9 }, notice: { padding: 10, borderRadius: 8, gap: 8, alignItems: 'center', backgroundColor: '#EEF5FA' },
});
