import { CartState } from '../../commerce/cartState';
import { AddressDraft, DeliveryMethod, PaymentMethod, SavedAddress } from '../../commerce/checkoutState';
import { PrototypeOrder } from '../../commerce/orderState';
import { VisualQaFixtureData, VisualQaScreenKey } from './visualQaTypes';

export const mockSavedAddresses: SavedAddress[] = [
  {
    id: 'address-1',
    name: 'Sarah Bennani',
    phone: '+212 6 61 23 45 67',
    addressLine: '12 Rue des Fleurs, Apt 4',
    city: 'Casablanca',
    postcode: '20000',
    zone: 'Grand Casablanca',
    isDefault: true,
  },
  {
    id: 'address-2',
    name: 'Karim Bennani',
    phone: '+212 6 62 88 99 00',
    addressLine: '45 Avenue Hassan II',
    city: 'Rabat',
    postcode: '10000',
    zone: 'Rabat-Salé-Kénitra',
    isDefault: false,
  },
];

export const mockCartState: CartState = {
  lines: [
    {
      id: 'item-1',
      productId: 101,
      name: 'Canapé Luna 3 Places',
      variant: 'Tissu bouclé · Beige',
      quantity: 1,
      unitPriceMad: 4500,
      imageUri: undefined,
    },
    {
      id: 'item-2',
      productId: 102,
      name: 'Fauteuil Nori Accent',
      variant: 'Velours · Vert Sauge',
      quantity: 1,
      unitPriceMad: 1800,
      imageUri: undefined,
    },
  ],
};

export const mockAddressDraftValid: AddressDraft = {
  name: 'Sarah Bennani',
  phone: '+212 6 61 23 45 67',
  addressLine: '12 Rue des Fleurs, Apt 4',
  apartment: 'Apt 4',
  city: 'Casablanca',
  postcode: '20000',
  zone: 'Grand Casablanca',
  deliveryInstructions: 'Sonnier à l’interphone Bennani',
  label: 'Maison',
  isDefault: true,
};

export const mockAddressDraftInvalid: AddressDraft = {
  name: '',
  phone: '06612345',
  addressLine: '',
  apartment: '',
  city: '',
  postcode: 'ABC',
  zone: '',
  deliveryInstructions: '',
  label: 'Maison',
  isDefault: false,
};

export const mockOrder: PrototypeOrder = {
  orderId: 'MAY-2026-88492',
  checkoutAttemptId: 'qa-fixture-key',
  createdAt: '2026-05-28T10:24:00.000Z',
  id: 'MAY-2026-88492',
  idempotencyKey: 'qa-fixture-key',
  createdAtLabel: '28 mai 2026 à 10:24',
  paymentReference: 'PAY-1746825127',
  paymentMethod: 'cmi',
  paymentStatus: 'prototype_pending_confirmation',
  deliveryMethod: 'standard',
  orderStatus: 'preparing',
  deliveryStatus: 'preparing',
  address: mockSavedAddresses[0],
  lines: mockCartState.lines.map((line) => ({
    orderLineId: line.id,
    productId: line.productId,
    name: line.name,
    variantLabel: line.variant,
    quantity: line.quantity,
    unitPriceMad: line.unitPriceMad,
    imageUri: line.imageUri,
    id: line.id,
    variant: line.variant,
  })),
  deliveryFeeMad: 0,
  discountMad: 0,
  totalMad: 6300,
  trackingEvents: [],
  packages: [],
  invoice: null,
};

export const visualQaFixtures: Record<VisualQaScreenKey, VisualQaFixtureData> = {
  '06-checkout-summary-4step-overview-v2-fr': {
    screenKey: '06-checkout-summary-4step-overview-v2-fr',
    figmaNodeId: '309:679',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-choose-address-saved-list-v2-fr': {
    screenKey: '06-choose-address-saved-list-v2-fr',
    figmaNodeId: '309:680',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-add-new-address-form-v2-fr': {
    screenKey: '06-add-new-address-form-v2-fr',
    figmaNodeId: '309:681',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-add-address-validation-errors-fr': {
    screenKey: '06-add-address-validation-errors-fr',
    figmaNodeId: '309:682',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftInvalid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-choose-delivery-standard-express-relay-v2-fr': {
    screenKey: '06-choose-delivery-standard-express-relay-v2-fr',
    figmaNodeId: '309:687',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-choose-payment-cmi-cod-wallet-v2-fr': {
    screenKey: '06-choose-payment-cmi-cod-wallet-v2-fr',
    figmaNodeId: '309:690',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '04-welcome-sign-in-create-account-guest-fr': {
    screenKey: '04-welcome-sign-in-create-account-guest-fr',
    figmaNodeId: '309:613',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'wallet',
    order: mockOrder,
  },
  '06-payment-step-intro-step3-v2-fr': {
    screenKey: '06-payment-step-intro-step3-v2-fr',
    figmaNodeId: '309:693',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-secure-payment-redirect-v2-fr': {
    screenKey: '06-secure-payment-redirect-v2-fr',
    figmaNodeId: '309:694',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-secure-payment-redirect-loading-fr': {
    screenKey: '06-secure-payment-redirect-loading-fr',
    figmaNodeId: '309:695',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-payment-verification-processing-fr': {
    screenKey: '06-payment-verification-processing-fr',
    figmaNodeId: '309:696',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-cash-on-delivery-confirmation-fr': {
    screenKey: '06-cash-on-delivery-confirmation-fr',
    figmaNodeId: '309:697',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cash-on-delivery',
    order: { ...mockOrder, paymentMethod: 'cash-on-delivery', paymentStatus: 'cash_on_delivery_pending' },
  },
  '06-payment-confirmed-success-v2-fr': {
    screenKey: '06-payment-confirmed-success-v2-fr',
    figmaNodeId: '309:698',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: { ...mockOrder, paymentStatus: 'confirmed' },
  },
  '06-payment-failed-retry-fr': {
    screenKey: '06-payment-failed-retry-fr',
    figmaNodeId: '309:699',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: { ...mockOrder, paymentStatus: 'failed' },
  },
  '06-payment-cancelled-resume-fr': {
    screenKey: '06-payment-cancelled-resume-fr',
    figmaNodeId: '309:700',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: { ...mockOrder, paymentStatus: 'cancelled' },
  },
  '06-order-review-confirm-multi-vendor-v2-fr': {
    screenKey: '06-order-review-confirm-multi-vendor-v2-fr',
    figmaNodeId: '309:703',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
  '06-order-processing-loading-state-fr': {
    screenKey: '06-order-processing-loading-state-fr',
    figmaNodeId: '309:706',
    cart: mockCartState,
    savedAddresses: mockSavedAddresses,
    selectedAddressId: 'address-1',
    addressDraft: mockAddressDraftValid,
    deliveryMethod: 'standard',
    paymentMethod: 'cmi',
    order: mockOrder,
  },
};
