<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * The technical dashboard was introduced with inline English labels. Keep
     * its source strings in the normal translation table so the active app
     * locale (French by default) is used consistently in Blade and Livewire.
     */
    public function up(): void
    {
        $translations = [
            // Dashboard shell and charts
            'MarketOps Dashboard' => 'Tableau de bord MarketOps',
            'System Live' => 'Système en ligne',
            'Updated just now' => 'Mis à jour à l’instant',
            'Today' => 'Aujourd’hui',
            '7D' => '7 j',
            '30D' => '30 j',
            '90D' => '90 j',
            'Overview' => 'Vue d’ensemble',
            'Vendors' => 'Vendeurs',
            'Finance' => 'Finance',
            'Marketing' => 'Marketing',
            'Security' => 'Sécurité',
            'Technical Analytics' => 'Analyse technique',
            'Technical Monitoring Dashboard' => 'Tableau de bord de surveillance technique',
            'Revenue' => 'Chiffre d’affaires',
            'Forecast' => 'Prévision',
            'Visits' => 'Visites',
            'Commission' => 'Commission',
            'Refunds' => 'Remboursements',
            'Refund %' => '% de remboursements',
            'Active' => 'Actifs',
            'New' => 'Nouveaux',
            'No revenue data available for this period' => 'Aucune donnée de chiffre d’affaires disponible pour cette période',

            // Overview
            'Total Revenue' => 'Chiffre d’affaires total',
            'Total Visits' => 'Total des visites',
            'Avg Session' => 'Session moyenne',
            'Conversion Rate' => 'Taux de conversion',
            'Bounce Rate' => 'Taux de rebond',
            'Revenue Analytics & Forecast' => 'Analyse et prévision du chiffre d’affaires',
            'Historical sales with 7-day predictive modeling' => 'Ventes historiques avec prévision sur 7 jours',
            'Traffic Composition' => 'Composition du trafic',
            'Session distribution by source' => 'Répartition des sessions par source',
            'Hourly Traffic' => 'Trafic horaire',
            'Visits per hour today' => 'Visites par heure aujourd’hui',
            'Conversion Funnel' => 'Entonnoir de conversion',
            'User journey breakdown' => 'Détail du parcours utilisateur',
            'Product View' => 'Consultation du produit',
            'Add to Cart' => 'Ajout au panier',
            'Checkout' => 'Commande',
            'Purchased' => 'Achetés',
            'Growth Velocity' => 'Dynamique de croissance',
            'Month-over-month trajectory' => 'Évolution mensuelle',
            'OUTPERFORMING' => 'AU-DESSUS DES OBJECTIFS',
            'GROWTH MOMENTUM' => 'DYNAMIQUE DE CROISSANCE',
            'Purchases' => 'Achats',
            'Bounce Exits' => 'Sorties après rebond',
            'Top Vendors' => 'Meilleurs vendeurs',
            'By revenue this period' => 'Par chiffre d’affaires sur la période',
            'Vendor' => 'Vendeur',
            'Orders' => 'Commandes',
            'Rating' => 'Évaluation',
            'No vendor data this period' => 'Aucune donnée vendeur pour cette période',
            'Vendor Growth' => 'Croissance des vendeurs',
            'Monthly acquisition & retention' => 'Acquisition et fidélisation mensuelles',
            'Sales by Category' => 'Ventes par catégorie',
            'Revenue distribution' => 'Répartition du chiffre d’affaires',
            'Vendor Directory' => 'Répertoire des vendeurs',
            'Real-time performance ranking' => 'Classement des performances en temps réel',
            'No vendor data' => 'Aucune donnée vendeur',
            'Revenue Analytics' => 'Analyse du chiffre d’affaires',
            'Historical sales trend' => 'Tendance historique des ventes',
            'Traffic Sources' => 'Sources de trafic',
            'Session distribution' => 'Répartition des sessions',
            'System Health' => 'État du système',
            'API & service status' => 'État de l’API et des services',
            'Service' => 'Service',
            'Uptime' => 'Disponibilité',
            'Latency' => 'Latence',
            'Status' => 'Statut',
            'OK' => 'OK',
            'Warn' => 'Avertissement',
            'Monitoring initializing...' => 'Initialisation de la surveillance…',
            'Automated Insights' => 'Informations automatiques',
            'Performance signals' => 'Signaux de performance',
            'All systems nominal' => 'Tous les systèmes sont nominaux',
            'Core API' => 'API principale',
            'Database' => 'Base de données',
            'Direct' => 'Direct',
            'Referral' => 'Référencement',
            'Google' => 'Google',
            'Facebook' => 'Facebook',
            'High Order Volume' => 'Volume élevé de commandes',
            'orders in the last hour.' => 'commandes au cours de la dernière heure.',
            'Pending Refunds' => 'Remboursements en attente',
            'refund requests awaiting review.' => 'demandes de remboursement en attente de vérification.',
            'Vendor Payouts Due' => 'Paiements vendeurs à effectuer',
            'vendors awaiting payout.' => 'vendeurs en attente de paiement.',

            // Finance
            'Gross GMV' => 'Ventes brutes (GMV)',
            'Net Revenue' => 'Chiffre d’affaires net',
            'Refund Rate' => 'Taux de remboursement',
            'Pending Payouts' => 'Paiements en attente',
            'vendors' => 'vendeurs',
            'Earnings & Outflows' => 'Revenus et sorties de fonds',
            'Commission vs Refunds' => 'Commissions et remboursements',
            'Profitability Pulse' => 'Indicateur de rentabilité',
            'Transaction health metrics' => 'Indicateurs de santé des transactions',
            'Refund Trend' => 'Évolution des remboursements',
            'Avg Order Val' => 'Valeur moy. de commande',
            'Items/Order' => 'Articles/commande',
            'Vendor Payouts' => 'Paiements vendeurs',
            'Awaiting reconciliation' => 'En attente de rapprochement',
            'Amount' => 'Montant',
            'Date' => 'Date',
            'Paid' => 'Payé',
            'Processing' => 'En traitement',
            'Pending' => 'En attente',
            'No payouts' => 'Aucun paiement',
            'Tax Collection' => 'Collecte des taxes',
            'Regional compliance' => 'Conformité régionale',
            'Region' => 'Région',
            'Collected' => 'Collecté',
            'Rate' => 'Taux',
            'Dynamic' => 'Dynamique',
            'Compliant' => 'Conforme',
            'Total Tax' => 'Total des taxes',
            'No tax data' => 'Aucune donnée fiscale',
            'Recent Vendor Payouts' => 'Paiements vendeurs récents',
            'No recent payouts found.' => 'Aucun paiement récent trouvé.',
            'Quality score timeline' => 'Évolution du score de qualité',

            // Marketing
            'Campaign Revenue' => 'Chiffre d’affaires des campagnes',
            'Active Coupons' => 'Coupons actifs',
            'Customer LTV' => 'Valeur vie client',
            'Campaign Performance' => 'Performance des campagnes',
            'Flash deals & promotions' => 'Ventes flash et promotions',
            'Campaign' => 'Campagne',
            'Channel' => 'Canal',
            'Flash Sale' => 'Vente flash',
            'Live' => 'En cours',
            'Ended' => 'Terminée',
            'No campaigns' => 'Aucune campagne',
            'Active Campaigns' => 'Campagnes actives',
            'ROI tracking via coupon attribution' => 'Suivi du ROI grâce à l’attribution des coupons',
            'No campaigns found.' => 'Aucune campagne trouvée.',
            'Acquisition' => 'Acquisition',
            'Marketing funnel' => 'Entonnoir marketing',
            'Campaign Visits' => 'Visites des campagnes',
            'Coupon Revenue' => 'Chiffre d’affaires des coupons',
            'Coupon Tracker' => 'Suivi des coupons',
            'Discount impact logs' => 'Historique de l’impact des remises',
            'Code' => 'Code',
            'Discount' => 'Remise',
            'Uses' => 'Utilisations',
            'Expires' => 'Expire le',
            'No coupons' => 'Aucun coupon',
            'Security Audit Logs' => 'Journaux d’audit de sécurité',
            'Administrative actions' => 'Actions administratives',
            'No security events logged.' => 'Aucun événement de sécurité enregistré.',
            'Auth Failures' => 'Échecs d’authentification',
            'Blocked attempts' => 'Tentatives bloquées',
            'Blocked Uploads' => 'Téléversements bloqués',
            'Sanitization events' => 'Événements de nettoyage',
            'Nominal' => 'Nominal',
            'Top Performance Leaders' => 'Meilleurs résultats',
            "Yesterday's snapshot" => 'Instantané d’hier',
            'Partner' => 'Partenaire',
            'ID' => 'ID',
            'N/A' => 'N/D',
            'Unknown' => 'Inconnu',
            'No vendor data available.' => 'Aucune donnée vendeur disponible.',
            'Marketing Insights' => 'Informations marketing',
            'Growth recommendations' => 'Recommandations de croissance',
            'Best Send Time' => 'Meilleur moment d’envoi',
            'Thursdays at 6:45 PM for highest CTR' => 'Le jeudi à 18 h 45 pour un CTR maximal',
            'Retargeting ROI' => 'ROI du reciblage',
            'Abandoned cart emails up 400%' => 'Les e-mails de panier abandonné progressent de 400 %',
            'Budget Advice' => 'Conseil budgétaire',
            'Shift 12% from Search to Social' => 'Déplacer 12 % de la recherche vers les réseaux sociaux',
            'Cohort Strategy' => 'Stratégie de cohorte',
            'Jan cohort shows peak LTV at M4' => 'La cohorte de janvier atteint sa valeur vie maximale au M4',

            // Security and status values
            'Secure' => 'Sécurisé',
            'Warning' => 'Avertissement',
            'Error' => 'Erreur',
            'Login' => 'Connexion',
            'Logout' => 'Déconnexion',
            'Failed Login' => 'Échec de connexion',
            'Malware Blocked' => 'Logiciel malveillant bloqué',
            'Unauthorized Access' => 'Accès non autorisé',
            'Failed Logins (24h)' => 'Échecs de connexion (24 h)',
            'Blocked Uploads (24h)' => 'Téléversements bloqués (24 h)',
            'Recent Security Events' => 'Événements de sécurité récents',
            'Audit logs for the last 24 hours' => 'Journaux d’audit des dernières 24 heures',
            'Time' => 'Heure',
            'Event' => 'Événement',
            'Admin' => 'Administrateur',
            'Action' => 'Action',
            'IP' => 'IP',
            'Admin/User' => 'Admin/utilisateur',
            'Action Type' => 'Type d’action',
            'Description' => 'Description',
            'IP Address' => 'Adresse IP',
            'No recent security events' => 'Aucun événement de sécurité récent',
            'Security Overview' => 'Vue d’ensemble de la sécurité',
            'System' => 'Système',
            'Blocked Malware (24h)' => 'Logiciels malveillants bloqués (24 h)',
            'Overall System Health' => 'État général du système',
            'No recent security events detected' => 'Aucun événement de sécurité récent détecté',

            // Operations and technical report
            'Operations & System Health' => 'Opérations et état du système',
            'Real-time observability and anomaly detection.' => 'Observabilité en temps réel et détection des anomalies.',
            'Pulse Dashboard' => 'Tableau de bord Pulse',
            'Horizon Console' => 'Console Horizon',
            'Payment Success (24h)' => 'Réussite des paiements (24 h)',
            'Based on total daily attempts' => 'Calculé sur le total des tentatives quotidiennes',
            'Horizon Status' => 'État de Horizon',
            'Active' => 'Actif',
            'Online' => 'En ligne',
            'Offline' => 'Hors ligne',
            'Background Queue Workers' => 'Workers de file d’attente en arrière-plan',
            'Failed Jobs' => 'Tâches échouées',
            'Tasks requiring intervention' => 'Tâches nécessitant une intervention',
            'Review Failed Jobs' => 'Consulter les tâches échouées',
            'Critical Anomalies' => 'Anomalies critiques',
            'Orders Shipped & Unpaid' => 'Commandes expédiées et impayées',
            'View Orders' => 'Voir les commandes',
            'Payment Reliability (7 Days)' => 'Fiabilité des paiements (7 jours)',
            'Daily CMI attempts vs payment failures' => 'Tentatives CMI quotidiennes et échecs de paiement',
            'Total Payment Attempts' => 'Total des tentatives de paiement',
            'CMI Failures' => 'Échecs CMI',
            'System Queue Backlog' => 'Arriéré de la file système',
            'Pending Images' => 'Images en attente',
            'Stuck Payments (24h)' => 'Paiements bloqués (24 h)',
            'Will be auto-expired by cron job.' => 'Seront expirés automatiquement par la tâche cron.',
            'Duplicate CMI Callbacks' => 'Callbacks CMI en double',
            'Successfully blocked by idempotency locks.' => 'Bloqués avec succès par les verrous d’idempotence.',
            'Technical Analytics Report' => 'Rapport d’analyse technique',
            'System Performance & Commerce Report' => 'Rapport de performance système et de commerce',
            'Generated on' => 'Généré le',
            'Period' => 'Période',
            'Last 7 Days' => '7 derniers jours',
            'Commerce Overview' => 'Vue d’ensemble du commerce',
            'Total Orders' => 'Total des commandes',
            'Avg Order Value' => 'Valeur moyenne de commande',
            'Technical Health' => 'Santé technique',
            'System Errors' => 'Erreurs système',
            'Avg Latency' => 'Latence moyenne',
            'Traffic Ingress Highlights' => 'Points forts du trafic entrant',
            'Page URL' => 'URL de la page',
            'Confidential Technical Audit - Mayush Platform Intelligence Engine' => 'Audit technique confidentiel - Moteur d’intelligence de la plateforme Mayush',
        ];

        foreach ($translations as $source => $french) {
            $key = preg_replace('/[^A-Za-z0-9\_]/', '', str_replace(' ', '_', strtolower($source)));

            DB::table('translations')->updateOrInsert(
                ['lang' => 'en', 'lang_key' => $key],
                ['lang_value' => $source, 'updated_at' => now(), 'created_at' => now()]
            );
            DB::table('translations')->updateOrInsert(
                ['lang' => 'fr', 'lang_key' => $key],
                ['lang_value' => $french, 'updated_at' => now(), 'created_at' => now()]
            );
        }

        Cache::forget('translations-en');
        Cache::forget('translations-fr');
    }

    public function down(): void
    {
        // Translation rows are shared application data; leave them intact on rollback.
    }
};
