<?php

return [
    'pruning_enabled' => false,

    'protected_tables' => [
        'addons',
        'addresses',
        'affiliate_configs',
        'affiliate_logs',
        'affiliate_payments',
        'affiliate_stats',
        'affiliate_users',
        'affiliate_withdraw_requests',
        'ai_prompts',
        'app_translations',
        'area_translations',
        'areas',
        'attribute_category',
        'attribute_translations',
        'attribute_values',
        'attributes',
        'banner_text_versions',
        'blog_categories',
        'blog_product',
        'blog_tag',
        'blog_translations',
        'blog_versions',
        'blogs',
        'brand_translations',
        'brands',
        'business_settings',
        'carrier_range_prices',
        'carrier_ranges',
        'carriers',
        'carts',
        'categories',
        'category_translations',
        'cities',
        'city_translations',
        'club_point_details',
        'club_points',
        'cmi_callback_logs',
        'colors',
        'combined_orders',
        'commission_histories',
        'contacts',
        'conversations',
        'countries',
        'coupon_usages',
        'coupons',
        'currencies',
        'custom_alerts',
        'custom_label_translations',
        'custom_labels',
        'custom_sale_alerts',
        'customer_package_payments',
        'customer_package_translations',
        'customer_packages',
        'customer_product_translations',
        'customer_products',
        'dynamic_popups',
        'element_styles',
        'element_translations',
        'element_types',
        'elements',
        'elite_subscriptions',
        'email_templates',
        'flash_deal_products',
        'flash_deal_translations',
        'flash_deals',
        'follow_sellers',
        'frequently_bought_products',
        'home_categories',
        'inventory_logs',
        'languages',
        'manual_payment_methods',
        'measurement_points',
        'messages',
        'migrations',
        'model_has_permissions',
        'model_has_roles',
        'note_translations',
        'notes',
        'notification_type_translations',
        'notification_types',
        'onessta_city_maps',
        'onessta_pickup_city_maps',
        'onessta_shipments',
        'onessta_tracking_events',
        'order_details',
        'order_tracking_histories',
        'orders',
        'otp_configurations',
        'page_translations',
        'pages',
        'payku_payments',
        'payku_transactions',
        'payment_attempts',
        'payment_informations',
        'payment_methods',
        'payment_tokens',
        'payments',
        'permissions',
        'pickup_addresses',
        'pickup_point_translations',
        'pickup_points',
        'point_assignment_logs',
        'point_templates',
        'preorder_products',
        'preorders',
        'product_categories',
        'product_collection_product',
        'product_collections',
        'product_queries',
        'product_stocks',
        'product_taxes',
        'product_translations',
        'products',
        'promotions',
        'proxypay_payments',
        'refund_requests',
        'reviews',
        'role_has_permissions',
        'role_translations',
        'roles',
        'seller_categories',
        'seller_documents',
        'seller_packages',
        'seller_withdraw_requests',
        'sellers',
        'shipping_box_sizes',
        'shipping_systems',
        'shops',
        'size_chart_details',
        'size_charts',
        'sms_templates',
        'social_credentials',
        'staff',
        'states',
        'stock_alert_subscriptions',
        'stock_subscriptions',
        'subscribers',
        'tags',
        'taxes',
        'ticket_replies',
        'tickets',
        'top_banner_translations',
        'top_banners',
        'transactions',
        'translations',
        'uploads',
        'user_coupons',
        'users',
        'vendor_performance_snapshots',
        'wallets',
        'warranties',
        'warranty_translations',
        'wholesale_prices',
        'wishlists',
        'zones',
    ],

    'archive_before_prune_tables' => [
        'ai_usage_logs',
        'analytics_daily_summaries',
        'analytics_summaries',
        'audit_logs',
        'blog_subscriber_logs',
        'email_verification_attempts',
        'firebase_notifications',
        'image_optimization_states',
        'last_viewed_products',
        'notifications',
        'onessta_webhook_logs',
        'product_views',
        'registration_verification_codes',
        'semantic_embeddings',
        'visitor_metrics',
    ],

    'direct_prune_candidate_tables' => [
        'failed_jobs',
        'health_metrics',
        'jobs',
        'password_resets',
        'personal_access_tokens',
        'pulse_aggregates',
        'pulse_entries',
        'pulse_values',
        'searches',
    ],

    'unknown_protected_tables' => [
        //
    ],

    'retention_days_suggestions' => [
        'failed_jobs' => 30,
        'jobs' => 7,
        'password_resets' => 1,
        'personal_access_tokens' => 90,
        'pulse_aggregates' => 30,
        'pulse_entries' => 14,
        'pulse_values' => 30,
        'health_metrics' => 30,
        'searches' => 90,
        'audit_logs' => 365,
        'notifications' => 180,
        'visitor_metrics' => 180,
        'product_views' => 180,
        'image_optimization_states' => 180,
        'onessta_webhook_logs' => 365,
    ],
];
