import React from 'react';
import { ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SavedAddress } from '../../commerce/checkoutState';
import { MayushLogo } from '../../design-system/components/brand/MayushLogo';
import { MayushIcon } from '../../design-system/components/navigation/MayushIcon';
import { MayushText } from '../../design-system/components/typography/MayushText';
import { useTheme } from '../../design-system/theme/useTheme';
import { colors } from '../../design-system/tokens/colors';

export interface AddressSelectionScreenProps {
  addresses: SavedAddress[];
  selectedAddressId: string;
  onBack: () => void;
  onSelect: (addressId: string) => void;
  onContinue: () => void;
  onAddAddress: () => void;
  onEdit?: (addressId: string) => void;
}

export const AddressSelectionScreen: React.FC<AddressSelectionScreenProps> = ({ addresses, selectedAddressId, onBack, onSelect, onContinue, onAddAddress, onEdit }) => {
  const { isRTL, language } = useTheme(); const ar = language === 'ar'; const direction = isRTL ? styles.reverse : undefined;
  return <View style={styles.screen} accessibilityLabel={ar ? '\u0627\u062e\u062a\u0631 \u0639\u0646\u0648\u0627\u0646\u064b\u0627' : 'Choisir une adresse'}>
    <View style={[styles.header,direction]}><TouchableOpacity onPress={onBack} style={styles.iconButton}><MayushIcon name={isRTL?'arrow-right':'arrow-left'} size={23} color={colors.brand.navy900}/></TouchableOpacity><MayushLogo width={140} height={41}/><View style={styles.iconButton}><MayushIcon name="shopping-bag" size={22} color={colors.brand.navy900}/></View></View>
    <ScrollView contentContainerStyle={styles.content}><View style={[styles.heading,direction]}><View style={styles.flex}><MayushText variant="pageTitle" color={colors.brand.navy900} style={isRTL&&styles.rtl}>{ar?'\u0627\u062e\u062a\u0631 \u0639\u0646\u0648\u0627\u0646\u064b\u0627':'Choisir une adresse'}</MayushText><MayushText variant="body" color={colors.neutral.gray700} style={isRTL&&styles.rtl}>{ar?'\u062d\u062f\u062f \u0627\u0644\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0630\u064a \u062a\u0631\u063a\u0628 \u0641\u064a \u0627\u0633\u062a\u0644\u0627\u0645 \u0637\u0644\u0628\u0643 \u0641\u064a\u0647.':'S\u00e9lectionnez l\u2019adresse o\u00f9 vous souhaitez recevoir votre commande.'}</MayushText></View><View style={styles.pin}><MayushIcon name="map-pin" size={24} color={colors.brand.navy900}/></View></View>
      {addresses.map((address)=><View key={address.id} style={styles.card}><View style={[styles.cardHead,direction]}><View style={styles.home}><MayushIcon name="home" size={25} color={colors.brand.navy900}/></View><View style={styles.flex}><View style={[styles.nameRow,direction]}><MayushText variant="sectionTitle" color={colors.brand.navy900}>{address.name}</MayushText><View style={[styles.radio,selectedAddressId===address.id&&styles.radioSelected]}>{selectedAddressId===address.id?<View style={styles.radioInner}/>:null}</View></View><MayushText variant="caption" color={colors.neutral.gray700}>{address.phone}</MayushText></View></View>{address.isDefault?<MayushText variant="caption" color={colors.brand.orange500} style={styles.defaultPill}>{ar?'\u0627\u0644\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0627\u0641\u062a\u0631\u0627\u0636\u064a':'Adresse par d\u00e9faut'}</MayushText>:null}<View style={styles.rule}/><Detail icon="map" text={address.addressLine}/><Detail icon="briefcase" text={`${address.city}, ${address.postcode}`}/><Detail icon="map-pin" text={`${ar?'\u0645\u0646\u0637\u0642\u0629 \u0627\u0644\u062a\u0648\u0635\u064a\u0644':'Zone de livraison'} : ${address.zone}`} accent/><View style={[styles.actions,direction]}><TouchableOpacity onPress={()=>onEdit?.(address.id)} style={styles.edit}><MayushIcon name="edit-2" size={16} color={colors.brand.navy900}/><MayushText variant="button" color={colors.brand.navy900}>{ar?'\u062a\u0639\u062f\u064a\u0644':'Modifier'}</MayushText></TouchableOpacity><TouchableOpacity onPress={()=>{onSelect(address.id);onContinue();}} style={styles.select}><MayushIcon name="check" size={17} color={colors.surface.white}/><MayushText variant="button" color={colors.surface.white}>{ar?'\u0627\u062e\u062a\u064a\u0627\u0631':'S\u00e9lectionner'}</MayushText></TouchableOpacity></View></View>)}
      <TouchableOpacity onPress={onAddAddress} style={[styles.add,direction]}><MayushIcon name="plus" size={18} color={colors.brand.orange500}/><MayushText variant="button" color={colors.brand.orange500}>{ar?'\u0625\u0636\u0627\u0641\u0629 \u0639\u0646\u0648\u0627\u0646 \u062c\u062f\u064a\u062f':'Ajouter une nouvelle adresse'}</MayushText></TouchableOpacity><View style={[styles.security,direction]}><MayushIcon name="shield" size={16} color={colors.brand.orange500}/><MayushText variant="caption" color={colors.neutral.gray700}>{ar?'\u0645\u0639\u0644\u0648\u0645\u0627\u062a\u0643 \u0622\u0645\u0646\u0629 \u0648\u0633\u0631\u064a\u0629.':'Vos informations sont s\u00e9curis\u00e9es et confidentielles.'}</MayushText></View>
    </ScrollView>
  </View>;
};

const Detail:React.FC<{icon:React.ComponentProps<typeof MayushIcon>['name'];text:string;accent?:boolean}>=({icon,text,accent})=><View style={styles.detail}><MayushIcon name={icon} size={15} color={accent?colors.brand.orange500:colors.brand.navy900}/><MayushText variant="caption" color={accent?colors.brand.orange500:colors.neutral.gray700} style={styles.flex}>{text}</MayushText></View>;
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.surface.white},header:{height:70,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},reverse:{flexDirection:'row-reverse'},rtl:{textAlign:'right',writingDirection:'rtl'},iconButton:{width:34,height:34,borderRadius:8,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF7EF'},content:{paddingHorizontal:19,paddingBottom:24},heading:{marginTop:9,flexDirection:'row',gap:10},flex:{flex:1},pin:{width:38,height:38,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF7EF'},card:{marginTop:13,padding:13,borderWidth:1,borderColor:'#F0E3D7',borderRadius:13,backgroundColor:colors.surface.white},cardHead:{flexDirection:'row',gap:12},home:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF7EF'},nameRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},radio:{width:19,height:19,borderRadius:10,borderWidth:1.5,borderColor:colors.brand.navy900,alignItems:'center',justifyContent:'center'},radioSelected:{borderColor:colors.brand.orange500},radioInner:{width:11,height:11,borderRadius:6,backgroundColor:colors.brand.orange500},defaultPill:{alignSelf:'flex-start',marginTop:8,paddingHorizontal:8,paddingVertical:4,borderRadius:5,backgroundColor:'#FFF6E8'},rule:{height:1,marginVertical:10,backgroundColor:'#F0E3D7'},detail:{marginTop:5,flexDirection:'row',gap:8},actions:{marginTop:12,flexDirection:'row',gap:12},edit:{flex:1,height:35,borderRadius:7,borderWidth:1,borderColor:colors.brand.navy900,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},select:{flex:1,height:35,borderRadius:7,backgroundColor:colors.brand.orange500,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},add:{height:44,marginTop:14,borderWidth:1,borderColor:colors.brand.orange500,borderRadius:8,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},security:{marginTop:15,alignSelf:'center',flexDirection:'row',alignItems:'center',gap:6}});
