import React from 'react';
import { ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native';
import { SavedAddress } from '../../commerce/checkoutState';
import { MayushLogo } from '../../design-system/components/brand/MayushLogo';
import { MayushIcon } from '../../design-system/components/navigation/MayushIcon';
import { MayushText } from '../../design-system/components/typography/MayushText';
import { useTheme } from '../../design-system/theme/useTheme';
import { colors } from '../../design-system/tokens/colors';

export interface AddressSelectionScreenProps {
  addresses: SavedAddress[];
  selectedAddressId: string;
  onBack: () => void;
  onSelect: (addressId: string) => void;
  onContinue: () => void;
  onAddAddress: () => void;
}

export const AddressSelectionScreen: React.FC<AddressSelectionScreenProps> = ({ addresses, selectedAddressId, onBack, onSelect, onContinue, onAddAddress }) => {
  const { isRTL, language } = useTheme();
  const copy = language === 'ar'
    ? { title: '\u0627\u062e\u062a\u0631 \u0639\u0646\u0648\u0627\u0646\u064b\u0627', subtitle: '\u062d\u062f\u062f \u0627\u0644\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0630\u064a \u062a\u0631\u063a\u0628 \u0641\u064a \u0627\u0633\u062a\u0644\u0627\u0645 \u0637\u0644\u0628\u0643 \u0641\u064a\u0647.', default: '\u0627\u0644\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0627\u0641\u062a\u0631\u0627\u0636\u064a', edit: '\u062a\u0639\u062f\u064a\u0644', select: '\u0627\u062e\u062a\u0631', secure: '\u0645\u0639\u0644\u0648\u0645\u0627\u062a\u0643 \u0622\u0645\u0646\u0629 \u0648\u0633\u0631\u064a\u0629.' }
    : { title: 'Choisir une adresse', subtitle: 'Sélectionnez l’adresse où vous souhaitez recevoir votre commande.', default: 'Adresse par défaut', edit: 'Modifier', select: 'Sélectionner', secure: 'Vos informations sont sécurisées et confidentielles.' };
  const direction = isRTL ? styles.rowReverse : undefined;

  return (
    <View style={styles.screen} accessibilityLabel={copy.title}>
      <View style={[styles.header, direction]}><TouchableOpacity accessibilityRole="button" accessibilityLabel={language === 'ar' ? '\u0631\u062c\u0648\u0639' : 'Retour'} onPress={onBack} style={styles.backButton}><MayushIcon name={isRTL ? 'arrow-right' : 'arrow-left'} size={23} color={colors.brand.navy900} /></TouchableOpacity><MayushLogo width={140} height={41} /><View style={styles.cartButton}><MayushIcon name="shopping-bag" size={23} color={colors.brand.navy900} /><View style={styles.badge}><MayushText variant="caption" color={colors.surface.white}>2</MayushText></View></View></View>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
        <View style={[styles.titleRow, direction]}><View style={styles.titleCopy}><MayushText variant="pageTitle" color={colors.brand.navy900} style={[styles.title, isRTL && styles.rtlText]}>{copy.title}</MayushText><MayushText variant="body" color={colors.neutral.gray700} style={[styles.subtitle, isRTL && styles.rtlText]}>{copy.subtitle}</MayushText></View><View style={styles.pinCircle}><MayushIcon name="map-pin" size={24} color={colors.brand.navy900} /></View></View>
        <View style={styles.addressList}>{addresses.map((address) => <AddressCard key={address.id} address={address} selected={selectedAddressId === address.id} copy={copy} direction={direction} isRTL={isRTL} onSelect={() => { onSelect(address.id); onContinue(); }} />)}</View>
        <TouchableOpacity accessibilityRole="button" onPress={onAddAddress} style={[styles.addAddress, direction]}><MayushIcon name="plus" size={18} color={colors.brand.orange500} /><MayushText variant="button" color={colors.brand.orange500}>{language === 'ar' ? 'إضافة عنوان جديد' : 'Ajouter une nouvelle adresse'}</MayushText></TouchableOpacity>
        <View style={[styles.security, direction]}><MayushIcon name="shield" size={15} color={colors.brand.orange500} /><MayushText variant="caption" color={colors.neutral.gray700}>{copy.secure}</MayushText></View>
      </ScrollView>
    </View>
  );
};

const AddressCard: React.FC<{ address: SavedAddress; selected: boolean; copy: Record<string, string>; direction: typeof styles.rowReverse | undefined; isRTL: boolean; onSelect: () => void }> = ({ address, selected, copy, direction, isRTL, onSelect }) => <View style={styles.card}><View style={[styles.cardHeading, direction]}><View style={styles.homeCircle}><MayushIcon name="home" size={27} color={colors.brand.navy900} /></View><View style={styles.cardName}><View style={[styles.nameRadio, direction]}><MayushText variant="sectionTitle" color={colors.brand.navy900} style={isRTL && styles.rtlText}>{address.name}</MayushText><View style={[styles.radio, selected && styles.radioSelected]}>{selected ? <View style={styles.radioInner} /> : null}</View></View><View style={[styles.phone, direction]}><MayushIcon name="phone" size={15} color={colors.brand.navy900} /><MayushText variant="body" color={colors.neutral.gray700}>{address.phone}</MayushText></View></View></View>{address.isDefault ? <View style={styles.defaultPill}><MayushIcon name="star" size={13} color={colors.brand.orange500} /><MayushText variant="caption" color={colors.brand.orange500}>{copy.default}</MayushText></View> : null}<View style={styles.rule} /><Detail icon="map" value={address.addressLine} /><Detail icon="briefcase" value={`${address.city}, ${address.postcode}`} /><Detail icon="map-pin" value={`${isRTL ? '\u0645\u0646\u0637\u0642\u0629 \u0627\u0644\u062a\u0648\u0635\u064a\u0644' : 'Zone de livraison'} : ${address.zone}`} accent /><View style={[styles.actions, direction]}><TouchableOpacity accessibilityRole="button" style={styles.editButton}><MayushIcon name="edit-2" size={16} color={colors.brand.navy900} /><MayushText variant="button" color={colors.brand.navy900} style={styles.actionLabel}>{copy.edit}</MayushText></TouchableOpacity><TouchableOpacity accessibilityRole="button" onPress={onSelect} style={styles.selectButton}><MayushIcon name="check" size={17} color={colors.surface.white} /><MayushText variant="button" color={colors.surface.white} style={styles.actionLabel}>{copy.select}</MayushText></TouchableOpacity></View></View>;
const Detail: React.FC<{ icon: React.ComponentProps<typeof MayushIcon>['name']; value: string; accent?: boolean }> = ({ icon, value, accent }) => <View style={styles.detail}><MayushIcon name={icon} size={15} color={accent ? colors.brand.orange500 : colors.brand.navy900} /><MayushText variant="caption" color={accent ? colors.brand.orange500 : colors.neutral.gray700} style={styles.detailText}>{value}</MayushText></View>;

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface.white }, rowReverse: { flexDirection: 'row-reverse' }, rtlText: { writingDirection: 'rtl', textAlign: 'right' },
  header: { height: 70, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, backButton: { width: 34, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF7EF' }, cartButton: { width: 34, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF7EF', position: 'relative' }, badge: { position: 'absolute', top: -4, right: -4, minWidth: 15, height: 15, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.brand.orange500 },
  content: { paddingHorizontal: 19, paddingBottom: 20 }, titleRow: { marginTop: 9, flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, titleCopy: { flex: 1 }, title: { fontSize: 24, lineHeight: 31 }, subtitle: { marginTop: 2, fontSize: 12, lineHeight: 17 }, pinCircle: { width: 37, height: 37, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF7EF' }, addressList: { marginTop: 17, gap: 12 }, addAddress: { height: 42, marginTop: 13, borderWidth: 1, borderColor: colors.brand.orange500, borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#FFFCF7' },
  card: { borderWidth: 1, borderColor: '#F0E3D7', borderRadius: 13, padding: 13, backgroundColor: colors.surface.white, shadowColor: colors.brand.navy900, shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 2 }, cardHeading: { flexDirection: 'row', gap: 12 }, homeCircle: { width: 50, height: 50, borderRadius: 25, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF7EF' }, cardName: { flex: 1 }, nameRadio: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, phone: { marginTop: 5, flexDirection: 'row', alignItems: 'center', gap: 6 }, radio: { width: 19, height: 19, borderRadius: 10, borderWidth: 1.5, borderColor: colors.brand.navy900, alignItems: 'center', justifyContent: 'center' }, radioSelected: { borderColor: colors.brand.orange500 }, radioInner: { width: 11, height: 11, borderRadius: 6, backgroundColor: colors.brand.orange500 }, defaultPill: { marginTop: -47, marginBottom: 23, alignSelf: 'flex-start', minHeight: 22, borderRadius: 5, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#FFF6E8' }, rule: { height: 1, marginVertical: 10, backgroundColor: '#F0E3D7' }, detail: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginTop: 5 }, detailText: { flex: 1, fontSize: 10, lineHeight: 14 }, actions: { marginTop: 12, flexDirection: 'row', gap: 12 }, editButton: { flex: 1, height: 33, borderRadius: 7, borderWidth: 1, borderColor: colors.brand.navy900, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, selectButton: { flex: 1, height: 33, borderRadius: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: colors.brand.orange500 }, actionLabel: { fontSize: 11 }, security: { marginTop: 15, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 6 },
});
