<?php

namespace App\Enums;

enum BotState: string
{
    case NEW = 'NEW';
    case BOT_GREETING = 'BOT_GREETING';
    case LANGUAGE_SELECTION = 'LANGUAGE_SELECTION';
    case INTENT_SELECTION = 'INTENT_SELECTION';
    case SUB_INTENT_SELECTION = 'SUB_INTENT_SELECTION';
    case COLLECTING_DATA = 'COLLECTING_DATA';
    case VALIDATING_DATA = 'VALIDATING_DATA';
    case FETCHING_CONTEXT = 'FETCHING_CONTEXT';
    case PROVIDING_SOLUTION = 'PROVIDING_SOLUTION';
    case WAITING_CONFIRMATION = 'WAITING_CONFIRMATION';
    case SECOND_ATTEMPT = 'SECOND_ATTEMPT';
    case ESCALATION_REQUIRED = 'ESCALATION_REQUIRED';
    case WAITING_FOR_AGENT = 'WAITING_FOR_AGENT';
    case AGENT_ASSIGNED = 'AGENT_ASSIGNED';
    case HUMAN_ACTIVE = 'HUMAN_ACTIVE';
    case PENDING_CUSTOMER = 'PENDING_CUSTOMER';
    case PENDING_SUPPORT = 'PENDING_SUPPORT';
    case RESOLVED_BY_BOT = 'RESOLVED_BY_BOT';
    case RESOLVED_BY_AGENT = 'RESOLVED_BY_AGENT';
    case CLOSED = 'CLOSED';
    case ABANDONED = 'ABANDONED';
    case SPAM = 'SPAM';
}
